routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('recette.index'));
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::resource('ingredient', 'IngredientController');
    Route::resource('unite', 'UniteController');
    Route::resource('panier', 'PanierController');
    Route::resource('user', 'UserController');
    Route::get('panier/{recette}-{personnes}', ['as' => 'panier.ajoute/{recette}-{personnes}', 'uses' => 'PanierController@ajouteRecette'])->where('recette', '[0-9]+')->where('personnes', '[0-9]+');
    Route::post('panier/{recette}', ['as' => 'panier.store/{recette}', 'uses' => 'PanierController@store']);
    Route::delete('panier', ['as' => 'panier.destroyAll', 'uses' => 'PanierController@destroyAll']);
    Route::get('liste-de-courses', ['as' => 'panier.liste', 'uses' => 'PanierController@liste']);
    Route::post('ingredient/recherche', ['as' => 'ingredient.recherche', 'uses' => 'IngredientController@recherche']);
    Route::post('unite/recherche', ['as' => 'unite.recherche', 'uses' => 'UniteController@recherche']);
    Route::post('user/recherche', ['as' => 'user.recherche', 'uses' => 'UserController@recherche']);
});

// Route::resource('user', 'UserController');
Route::resource('recette', 'RecetteController');
Route::resource('recette_etape', 'RecetteEtapeController');
Route::resource('recette_ingredient_unite', 'RecetteIngredientUniteController');
Route::post('recette/recherche', ['as' => 'recette.recherche', 'uses' => 'RecetteController@recherche']);
Route::get('recette_etape/{recette}/create', ['as' => 'recette_etape.create/{recette}', 'uses' => 'RecetteEtapeController@create']);
Route::get('recette_ingredient_unite/{recette}/create', ['as' => 'recette_ingredient_unite.create/{recette}', 'uses' => 'RecetteIngredientUniteController@create']);

Route::get('deconnexion', ['as' => 'deconnexion', function() {
    Auth::logout();
}]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('image-upload', 'ImageUploadController@imageUpload')->name('image.upload');
Route::post('image-upload', 'ImageUploadController@imageUploadPost')->name('image.upload.post');

resources/views/home.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            Vous êtes connecté !
        </div>
    </div>
</div>
@endsection

resources/views/imageUpload.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.7 image upload example - HDTuto.com</title>
    <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.css">
</head>
<body>
<div class="container">
    <div class="panel panel-primary">
      <div class="panel-heading"><h2>Laravel 5.7 image upload example - HDTuto.com</h2></div>
      <div class="panel-body">
        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
        </div>
        <img src="images/{{ Session::get('image') }}">
        @endif

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('image.upload.post') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-success">Upload</button>
                </div>
            </div>
        </form>
      </div>
    </div>
</div>
</body>
</html>

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	<a class="navbar-brand" href="{{ route('panier.liste')}}">Ma liste de courses</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item{{ (isset($titre) && $titre == "Recettes")?" active":"" }}">
				<a class="nav-link" href="{{ route('recette.index')}}">
					<i class="fas fa-hamburger"></i>
					RECETTES
				</a>
			</li>
			@if (Auth::check())
				<li class="nav-item{{ (isset($titre) && $titre == "Ingrédients")?" active":"" }}">
					<a class="nav-link" href="{{ route('ingredient.index')}}">
						<i class="fas fa-apple-alt"></i>
						INGREDIENTS
					</a>
				</li>
				<li class="nav-item{{ (isset($titre) && $titre == "Unités")?" active":"" }}">
					<a class="nav-link" href="{{ route('unite.index')}}">
						<i class="fas fa-weight"></i>
						UNITES
					</a>
				</li>
			@endif
		</ul>
		@if (Auth::check())
		<ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
			<li class="nav-item{{ (isset($titre) && $titre == "Panier")?" active":"" }}">
				<a class="nav-link" href="{{ route('panier.index')}}">
					<i class="fas fa-shopping-cart"></i>
					MON PANIER
				</a>
			</li>
			@if (Auth::user()->isAdmin())
			<li class="nav-item{{ (isset($titre) && $titre == "Administration")?" active":"" }}">
				<a class="nav-link" href="{{ route('user.index')}}">
					<i class="fas fa-users"></i>
					ADMINISTRATION
				</a>
			</li>
			@endif
			<li class="nav-item{{ (isset($titre) && $titre == "Utilisateur")?" active":"" }}">
				<a class="nav-link" href="{{ route('user.show', Auth::id())}}">
					<i class="fas fa-user-circle"></i>
					MON COMPTE
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" 
					href="{{ route('deconnexion') }}"
					onclick="event.preventDefault();
							 document.getElementById('logout-form').submit();">
					<i class="fas fa-power-off"></i>
					DECONNEXION
				</a>
				<form id="logout-form" action="{{ url('logout') }}" method="POST" style="display: none;">
					{{ csrf_field() }}
				</form>
			</li>
		</ul>
		@else
		<ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
			<li class="nav-item{{ (isset($titre) && $titre == "Inscription")?" active":"" }}">
				<a class="nav-link" href="{{ route('register')}}">
					<i class="fas fa-user-plus"></i>
					INSCRIPTION
				</a>
			</li>
			<li class="nav-item{{ (isset($titre) && $titre == "Connexion")?" active":"" }}">
				<a class="nav-link" href="{{ route('login')}}">
					<i class="fas fa-sign-in-alt"></i>
					CONNEXION
				</a>
			</li>
		</ul>
		@endif
	</div>
</nav>