routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('recette.index'));
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::resource('ingredient', 'IngredientController');
    Route::resource('unite', 'UniteController');
    Route::resource('panier', 'PanierController');
    Route::resource('user', 'UserController');
    Route::get('panier/{recette}-{personnes}', ['as' => 'panier.ajoute/{recette}-{personnes}', 'uses' => 'PanierController@ajouteRecette'])->where('recette', '[0-9]+')->where('personnes', '[0-9]+');
    Route::post('panier/{recette}', ['as' => 'panier.store/{recette}', 'uses' => 'PanierController@store']);
    Route::delete('panier', ['as' => 'panier.destroyAll', 'uses' => 'PanierController@destroyAll']);
    Route::get('liste-de-courses', ['as' => 'panier.liste', 'uses' => 'PanierController@liste']);
    Route::post('ingredient/recherche', ['as' => 'ingredient.recherche', 'uses' => 'IngredientController@recherche']);
    Route::post('unite/recherche', ['as' => 'unite.recherche', 'uses' => 'UniteController@recherche']);
    Route::post('user/recherche', ['as' => 'user.recherche', 'uses' => 'UserController@recherche']);
});

// Route::resource('user', 'UserController');
Route::resource('recette', 'RecetteController');
Route::resource('recette_etape', 'RecetteEtapeController');
Route::resource('recette_ingredient_unite', 'RecetteIngredientUniteController');
Route::post('recette/recherche', ['as' => 'recette.recherche', 'uses' => 'RecetteController@recherche']);
Route::get('recette_etape/{recette}/create', ['as' => 'recette_etape.create/{recette}', 'uses' => 'RecetteEtapeController@create']);
Route::get('recette_ingredient_unite/{recette}/create', ['as' => 'recette_ingredient_unite.create/{recette}', 'uses' => 'RecetteIngredientUniteController@create']);

Route::get('deconnexion', ['as' => 'deconnexion', function() {
    Auth::logout();
}]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('image-upload', 'ImageUploadController@imageUpload')->name('image.upload');
Route::post('image-upload', 'ImageUploadController@imageUploadPost')->name('image.upload.post');

app/Recette.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image;

class Recette extends Model
{
    protected $fillable = ['nom', 'description', 'temps', 'image', 'personnes'];

    public function getImageAttribute($value)
    {
        $image = Image::find($value);
        return $image['nom'];
    }

    public function scopeIdDescending($query)
    {
        return $query->orderBy('id','DESC');
    }
}

app/Http/Controllers/RecetteController.php
<?php

namespace App\Http\Controllers;

use App\Recette;
use Illuminate\Http\Request;
use App\Image;
use App\Ingredient;
use App\Recette_ingredient_unite;
use App\Recette_etape;
use DB;

class RecetteController extends Controller
{
    protected $titre = "Recettes";
    protected $taille_max = 300;
    protected $taille_max_album = 250;

    public function __construct()
    {
        $this->middleware('isAdmin')->only(['edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $titre = $this->titre;
        $height_max = $this->taille_max_album;
        $recettes = Recette::idDescending()->get();
        $tailles_images = [];
        foreach($recettes as $recette)
        {
            list($width, $height, $type, $attr) = getimagesize("images/" . $recette['image']);
            if($height > $height_max)
            {
                $width = ($height_max / $height) * $width;
                $height = $height_max;
            }
            $tailles_images[$recette['id']]['width'] = $width;
            $tailles_images[$recette['id']]['height'] = $height;
        }
        return view('recettes.index', compact('recettes', 'titre', 'tailles_images', 'height_max'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titre = $this->titre;
        return view('recettes.create', compact('titre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:8192',
        ]);
        $nom = time().'.'.$request->image->getClientOriginalExtension();
		$request->image->move(public_path('images'), $nom);
        $image_id = Image::create(['nom' => $nom])->id;
        $recette = Recette::create(['nom' => $request->nom, 'description' => $request->description, 'temps' => $request->temps, 'image' => $image_id, 'personnes' => $request->personnes]);
        return redirect(route('recette.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Recette  $recette
     * @return \Illuminate\Http\Response
     */
    public function show(Recette $recette)
    {
        $height_max = $this->taille_max;
        $tailles_image = [];
        list($width, $height, $type, $attr) = getimagesize("images/" . $recette['image']);
        if($height > $height_max)
        {
            $width = ($height_max / $height) * $width;
            $height = $height_max;
        }
        $tailles_image['width'] = $width;
        $tailles_image['height'] = $height;

        $titre = $this->titre;
        $etapes = Recette_etape::etapeAscending()->where('recette', $recette['id'])->get();
        $recette_ingredient_unites = DB::table('recette_ingredient_unites')
            ->join('ingredients', 'ingredients.id', '=', 'recette_ingredient_unites.ingredient')
            ->join('unites', 'unites.id', '=', 'recette_ingredient_unites.unite')
            ->select('recette_ingredient_unites.*', 'ingredients.nom as nom_ingredient', 'unites.nom as nom_unite', 'unites.abreviation as abr_unite')
            ->where('recette', $recette['id'])
            ->get();
        return view('recettes.show', compact('recette', 'titre', 'etapes', 'recette_ingredient_unites', 'tailles_image'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Recette  $recette
     * @return \Illuminate\Http\Response
     */
    public function edit(Recette $recette)
    {
        $titre = $this->titre;

        $height_max = $this->taille_max;
        $tailles_image = [];
        list($width, $height, $type, $attr) = getimagesize("images/" . $recette['image']);
        if($height > $height_max)
        {
            $width = ($height_max / $height) * $width;
            $height = $height_max;
        }
        $tailles_image['width'] = $width;
        $tailles_image['height'] = $height;

        $etapes = Recette_etape::etapeAscending()->where('recette', $recette['id'])->get();
        $recette_ingredient_unites = DB::table('recette_ingredient_unites')
            ->join('ingredients', 'ingredients.id', '=', 'recette_ingredient_unites.ingredient')
            ->join('unites', 'unites.id', '=', 'recette_ingredient_unites.unite')
            ->select('recette_ingredient_unites.*', 'ingredients.nom as nom_ingredient', 'unites.nom as nom_unite', 'unites.abreviation as abr_unite')
            ->where('recette', $recette['id'])
            ->get();
        return view('recettes.edit', compact('recette', 'titre', 'etapes', 'recette_ingredient_unites', 'tailles_image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Recette  $recette
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Recette $recette)
    {
        if($request->image != null)
        {
            $request->validate([
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:8192',
            ]);
            $nom = time().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('images'), $nom);
            $image_id = Image::create(['nom' => $nom])->id;
            $recette->update(['nom' => $request->nom, 'description' => $request->description, 'temps' => $request->temps, 'image' => $image_id, 'personnes' => $request->personnes]);
        }
        else
            $recette->update(['nom' => $request->nom, 'description' => $request->description, 'temps' => $request->temps, 'personnes' => $request->personnes]);
        return redirect(route('recette.edit', $recette));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Recette  $recette
     * @return \Illuminate\Http\Response
     */
    public function destroy(Recette $recette)
    {
        $recette->delete();
        return redirect(route('recette.index'));
    }
    
    public function recherche(Request $request)
    {
        $titre = $this->titre;
        $height_max = 225;
        $recherche = $request->recherche;
        $recettes = Recette::where('nom', 'LIKE', '%' . $recherche . '%')->idDescending()->get();
        $tailles_images = [];
        foreach($recettes as $recette)
        {
            list($width, $height, $type, $attr) = getimagesize("images/" . $recette['image']);
            if($height > $height_max)
            {
                $width = ($height_max / $height) * $width;
                $height = $height_max;
            }
            $tailles_images[$recette['id']]['width'] = $width;
            $tailles_images[$recette['id']]['height'] = $height;
        }
        return view('recettes.index', compact('recettes', 'titre', 'tailles_images', 'height_max', 'recherche'));
    }
}

resources/views/recettes/create.blade.php
@extends('layouts.default')

@section('content')
	<h2>Ajouter une nouvelle recette</h2>
	{!! Form::open(['url' => route('recette.store'), "enctype" => "multipart/form-data"]) !!}
		<div class="form-group">
			{!! Form::label('nom', 'Nom : ') !!}
			{!! Form::text('nom', null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('description', 'Description : ') !!}
			{!! Form::textArea('description', null, ['class' => 'form-control', 'rows' => 1]) !!}
		</div>
		<div class="form-group">
			{!! Form::label('temps', 'Temps : ') !!}
			{!! Form::text('temps', null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('personnes', 'Personnes : ') !!}
			{!! Form::number('personnes', 0, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			<div class="custom-file">
				{!! Form::file('image', ['class' => 'custom-file-input']) !!}
				{!! Form::label('image', null, ['class' => 'custom-file-label']) !!}
			</div>
		</div>
		<button class="btn btn-primary">Ajouter</button>
	{!! Form::close() !!}
@endsection

@section('titre', $titre)

resources/views/recettes/edit.blade.php
@extends('layouts.default')

@section('content')
<h2>Editer la recette</h2>
<div class='row'>
	<div class='col-6'>
		{!! Form::open(['method' => 'put', 'url' => route('recette.update', $recette), 'class' => 'mb-2', "enctype" => "multipart/form-data"]) !!}
			<div class="form-group">
				{!! Form::label('nom', 'Nom : ') !!}
				{!! Form::text('nom', $recette['nom'], ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
				{!! Form::label('description', 'Description : ') !!}
				{!! Form::textArea('description', $recette['description'], ['class' => 'form-control', 'rows' => 2]) !!}
			</div>
			<div class="form-group">
				{!! Form::label('temps', 'Temps : ') !!}
				{!! Form::text('temps', $recette['temps'], ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
				{!! Form::label('personnes', 'Personnes : ') !!}
				{!! Form::number('personnes', $recette['personnes'], ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
				<div class="custom-file">
					{!! Form::file('image', ['class' => 'custom-file-input']) !!}
					{!! Form::label('image', null, ['class' => 'custom-file-label']) !!}
				</div>
			</div>
			<button class="btn btn-success">Modifier</button>
		{!! Form::close() !!}
	</div>
	<div class="col-6 d-block">
		<div class='align-middle' style='width: {{ $tailles_image['width'] }}px;'>
			<img style="width: {{ $tailles_image['width'] }}px;height: {{ $tailles_image['height'] }}px;" class="mx-auto figure-img img-thumbnail border-0 rounded card-img-top" src="http://{{ request()->getHost() }}/images/{{ $recette['image'] }}" alt="{{ $recette['nom'] }}">
		</div>
	</div>
</div>
	@include('recettes.ingredients.index')
	@include('recettes.etapes.index')
@endsection

@section('titre', $titre)

resources/views/recettes/index.blade.php
@extends('layouts.default')

@section('titre', $titre)

@section('content')
	<h2>Liste des recettes</h2>
	<div class="d-flex justify-content-between mt-3">
		{!! Form::open(['url' => 'recette/recherche', 'method' => 'POST', 'class' => 'form-inline mt-2 mt-md-0']) !!}
			{{ Form::text('recherche', $recherche??null, ['class' => 'form-control', 'placeholder' => 'Recette']) }}
			{{ Form::submit('Rechercher', ['class' => 'btn btn-outline-secondary my-2 my-sm-0'])}}
		{!! Form::close() !!}
	</div>
	@if (isset($recettes) && count($recettes) != 0)
	<main role="main">
		<div class="album py-5">
			<div class="container">
				<div class="row">
				@if (Auth::check() && Auth::user()->isAdmin())
					<div class="col-md-4">
						<a class="card mb-4 box-shadow" href="{{ route('recette.create') }}">
						<img style="height: {{ $height_max }}px; width: {{ $height_max }}px" class="mx-auto figure-img img-thumbnail border-0 rounded card-img-top" src="http://{{ request()->getHost() }}/assets/images/plus.png" alt="Ajouter une recette">
						  <div class="card-body">
							<p class="card-text text-center">
								Ajouter une recette
							</p>
						  </div>
						</a>
					</div>
				@endif
				@foreach ($recettes as $recette)
					<div class="col-md-4">
						<div class="card mb-4 box-shadow">
						<a href="{{ route('recette.show', $recette) }}" style="height: {{ $tailles_images[$recette['id']]['height'] }}px;" class="mx-auto">
							<img style="width: {{ $tailles_images[$recette['id']]['width'] }}px;height: {{ $tailles_images[$recette['id']]['height'] }}px;" class="mx-auto figure-img img-thumbnail border-0 rounded card-img-top" src="http://{{ request()->getHost() }}/images/{{ $recette['image'] }}" alt="{{ $recette['nom'] }}">
						</a>
						<div class="card-body">
							<h5 class="card-title">
							{{ $recette['nom'] }}
							(
								@for ($i = 0; $i < $recette['personnes']; $i++)
									<i class="fas fa-user"></i>
								@endfor
							)
							</h5>
							<p class="card-text">
								{{ $recette['description'] }}
							</p>
							<div class="d-flex justify-content-between align-items-center">
								<div >
									<a href="{{ route('recette.show', $recette) }}" type="button" class="btn btn-sm btn-outline-secondary">Voir</a>
									@if (Auth::check() && Auth::user()->isAdmin())
										<a href="{{ route('recette.edit', $recette) }}" type="button" class="btn btn-sm btn-outline-success">Modifier</a>
										{!! Form::open(['action' => ['RecetteController@destroy', $recette], 'method' => 'POST', 'class' => 'd-inline-block']) !!}
											{{ Form::hidden('_method', 'DELETE') }}
											{{ Form::submit('Supprimer', ['class' => 'btn btn-sm btn-outline-danger rounded-right'])}}
										{!! Form::close() !!}
									@endif
								</div>
								<small class="text-muted">{{ $recette['created_at']->diffForHumans() }}</small>
							</div>
						</div>
						</div>
					</div>
				@endforeach
			</div>
		</div>
		</div>
	</main>
	@else
	<div>
		Aucune recette dans la base de donnée !
	</div>
	@endif
@endsection

resources/views/recettes/show.blade.php
@extends('layouts.default')

@section('content')
	<div>
		<h2 class='mb-3 d-flex align-items-center justify-content-center'>
			{{ $recette['nom'] }} 
			(
				@for ($i = 0; $i < $recette['personnes']; $i++)
					<i class="fas fa-user"></i>
				@endfor
			)
			- {{ $recette['temps'] }}
		</h2>
	</div>
	<div>
		<div class="mb-2 d-block">
			<div class='mx-auto' style='width: {{ $tailles_image['width'] }}px;'>
				<img style="width: {{ $tailles_image['width'] }}px;height: {{ $tailles_image['height'] }}px;" class="mx-auto figure-img img-thumbnail border-0 rounded card-img-top" src="http://{{ request()->getHost() }}/images/{{ $recette['image'] }}" alt="{{ $recette['nom'] }}">
			</div>
			<div class='text-center'>
				<i>{{ $recette['description'] }}</i>
			</div>
		</div>
	</div>
	@include('recettes.ingredients.show')
	@include('recettes.etapes.show')
	@if (Auth::check())
		{!! Form::open(['method' => 'POST', 'url' => 'admin/panier/'.$recette['id'], 'class' => 'form-inline']) !!}
			<div class="form-group mx-sm-3 mb-2">
				{!! Form::label('personnes', 'Personnes : ', ['class' => 'form-group mb-2 mr-2']) !!}
				{!! Form::number('personnes', $recette['personnes'], ['class' => 'form-control']) !!}
			</div>
			<button class="btn btn-primary mb-2">Ajouter au panier</button>
		{!! Form::close() !!}
	@endif
@endsection

@section('titre', $titre)