routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('recette.index'));
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::resource('ingredient', 'IngredientController');
    Route::resource('unite', 'UniteController');
    Route::resource('panier', 'PanierController');
    Route::resource('user', 'UserController');
    Route::get('panier/{recette}-{personnes}', ['as' => 'panier.ajoute/{recette}-{personnes}', 'uses' => 'PanierController@ajouteRecette'])->where('recette', '[0-9]+')->where('personnes', '[0-9]+');
    Route::post('panier/{recette}', ['as' => 'panier.store/{recette}', 'uses' => 'PanierController@store']);
    Route::delete('panier', ['as' => 'panier.destroyAll', 'uses' => 'PanierController@destroyAll']);
    Route::get('liste-de-courses', ['as' => 'panier.liste', 'uses' => 'PanierController@liste']);
    Route::post('ingredient/recherche', ['as' => 'ingredient.recherche', 'uses' => 'IngredientController@recherche']);
    Route::post('unite/recherche', ['as' => 'unite.recherche', 'uses' => 'UniteController@recherche']);
    Route::post('user/recherche', ['as' => 'user.recherche', 'uses' => 'UserController@recherche']);
});

// Route::resource('user', 'UserController');
Route::resource('recette', 'RecetteController');
Route::resource('recette_etape', 'RecetteEtapeController');
Route::resource('recette_ingredient_unite', 'RecetteIngredientUniteController');
Route::post('recette/recherche', ['as' => 'recette.recherche', 'uses' => 'RecetteController@recherche']);
Route::get('recette_etape/{recette}/create', ['as' => 'recette_etape.create/{recette}', 'uses' => 'RecetteEtapeController@create']);
Route::get('recette_ingredient_unite/{recette}/create', ['as' => 'recette_ingredient_unite.create/{recette}', 'uses' => 'RecetteIngredientUniteController@create']);

Route::get('deconnexion', ['as' => 'deconnexion', function() {
    Auth::logout();
}]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('image-upload', 'ImageUploadController@imageUpload')->name('image.upload');
Route::post('image-upload', 'ImageUploadController@imageUploadPost')->name('image.upload.post');

app/Ingredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    protected $fillable = ['nom'];
}

app/Http/Controllers/Admin/IngredientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Ingredient;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IngredientController extends Controller
{
    protected $titre = "Ingrédients";

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('isAdmin')->only(['store', 'create', 'edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $titre = $this->titre;
        $ingredients = Ingredient::orderBy('nom', 'ASC')->get();
        return view('ingredients.index', compact('ingredients', 'titre'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titre = $this->titre;
        return view('ingredients.create', compact('titre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ingredient = Ingredient::create(['nom' => $request->nom]);
        return redirect(route('ingredient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function show(Ingredient $ingredient)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        $titre = $this->titre;
        return view('ingredients.edit', compact('ingredient', 'titre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ingredient $ingredient)
    {
        $ingredient->update($request->all());
        return redirect(route('ingredient.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->delete();
        return redirect(route('ingredient.index'));
    }

    public function recherche(Request $request)
    {
        $titre = $this->titre;
        $recherche = $request->recherche;
        $ingredients = Ingredient::where('nom', 'LIKE', '%' . $recherche . '%')->orWhere('id', 'LIKE', $recherche)->orderBy('nom', 'ASC')->get();
        return view('ingredients.index', compact('ingredients', 'titre', 'recherche'));
    }
}

resources/views/ingredients/create.blade.php
@extends('layouts.default')

@section('content')
	<h2>Ajouter un nouvel ingrédient</h2>
	{!! Form::open(['url' => route('ingredient.store')]) !!}
		<div class="form-group">
			{!! Form::label('nom', 'Nom : ') !!}
			{!! Form::text('nom', null, ['class' => 'form-control']) !!}
		</div>
		<button class="btn btn-primary">Ajouter</button>
	{!! Form::close() !!}
@endsection

@section('titre', $titre)

resources/views/ingredients/edit.blade.php
@extends('layouts.default')

@section('content')
	<h2>Editer l'ingrédient</h2>
	{!! Form::open(['method' => 'put', 'url' => route('ingredient.update', $ingredient)]) !!}
		<div class="form-group">
			{!! Form::label('nom', 'Nom : ') !!}
			{!! Form::text('nom', $ingredient['nom'], ['class' => 'form-control']) !!}
		</div>
		<button class="btn btn-primary">Modifier</button>
	{!! Form::close() !!}
@endsection

@section('titre', $titre)

resources/views/ingredients/index.blade.php
@extends('layouts.default')

@section('content')
	<h2>Liste des ingrédients</h2>
	<div class="d-flex justify-content-between mt-3">
		{!! Form::open(['url' => 'admin/ingredient/recherche', 'method' => 'POST', 'class' => 'form-inline mt-2 mt-md-0']) !!}
			{{ Form::text('recherche', $recherche??null, ['class' => 'form-control', 'placeholder' => 'Ingrédient']) }}
			{{ Form::submit('Rechercher', ['class' => 'btn btn-outline-secondary my-2 my-sm-0'])}}
		{!! Form::close() !!}
		@if (Auth::check() && Auth::user()->isAdmin())
		<a class="btn btn-primary" href="{{ route('ingredient.create') }}">Ajouter un ingrédient</a>
		@endif
	</div>
	@if (isset($ingredients) && count($ingredients) != 0)
	<div>
		<table class="table table-striped table-hover text-center">
			<thead class="thead-dark">
				<tr>
					@if (Auth::check() && Auth::user()->isAdmin())
					<th scope="col">Id</th>
					@endif
					<th scope="col">Nom</th>
					@if (Auth::check() && Auth::user()->isAdmin())
					<th scope="col">Actions</th>
					@endif
				</tr>
			</thead>
			<tbody>
			@foreach ($ingredients as $ingredient)
				<tr>
					@if (Auth::check() && Auth::user()->isAdmin())
					<td>{{ $ingredient['id'] }}</td>
					@endif
					<td>{{ $ingredient['nom'] }}</td>
					@if (Auth::check() && Auth::user()->isAdmin())
					<td>
						<div>
							<a class="d-inline-block btn btn-success" href="{{ route('ingredient.edit', ['ingredient' => $ingredient]) }}">Modifier</a>
							{!! Form::open(['action' => ['Admin\IngredientController@destroy', 'ingredient' => $ingredient], 'method' => 'POST', 'class' => 'd-inline-block']) !!}
								{{ Form::hidden('_method', 'DELETE') }}
								{{ Form::submit('Supprimer', ['class' => 'btn btn-danger'])}}
							{!! Form::close() !!}
						</div>
					</td>
					@endif
				</tr>
			@endforeach
			</tbody>
		</table>
	</div>
	@else
	<div>
		Aucun ingrédient dans la base de donnée !
	</div>
	@endif
@endsection

@section('titre', $titre)