routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('recette.index'));
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    Route::resource('ingredient', 'IngredientController');
    Route::resource('unite', 'UniteController');
    Route::resource('panier', 'PanierController');
    Route::resource('user', 'UserController');
    Route::get('panier/{recette}-{personnes}', ['as' => 'panier.ajoute/{recette}-{personnes}', 'uses' => 'PanierController@ajouteRecette'])->where('recette', '[0-9]+')->where('personnes', '[0-9]+');
    Route::post('panier/{recette}', ['as' => 'panier.store/{recette}', 'uses' => 'PanierController@store']);
    Route::delete('panier', ['as' => 'panier.destroyAll', 'uses' => 'PanierController@destroyAll']);
    Route::get('liste-de-courses', ['as' => 'panier.liste', 'uses' => 'PanierController@liste']);
    Route::post('ingredient/recherche', ['as' => 'ingredient.recherche', 'uses' => 'IngredientController@recherche']);
    Route::post('unite/recherche', ['as' => 'unite.recherche', 'uses' => 'UniteController@recherche']);
    Route::post('user/recherche', ['as' => 'user.recherche', 'uses' => 'UserController@recherche']);
});

// Route::resource('user', 'UserController');
Route::resource('recette', 'RecetteController');
Route::resource('recette_etape', 'RecetteEtapeController');
Route::resource('recette_ingredient_unite', 'RecetteIngredientUniteController');
Route::post('recette/recherche', ['as' => 'recette.recherche', 'uses' => 'RecetteController@recherche']);
Route::get('recette_etape/{recette}/create', ['as' => 'recette_etape.create/{recette}', 'uses' => 'RecetteEtapeController@create']);
Route::get('recette_ingredient_unite/{recette}/create', ['as' => 'recette_ingredient_unite.create/{recette}', 'uses' => 'RecetteIngredientUniteController@create']);

Route::get('deconnexion', ['as' => 'deconnexion', function() {
    Auth::logout();
}]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('image-upload', 'ImageUploadController@imageUpload')->name('image.upload');
Route::post('image-upload', 'ImageUploadController@imageUploadPost')->name('image.upload.post');

app/Unite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unite extends Model
{
    protected $fillable = ['nom', 'abreviation'];
}

app/Http/Controllers/Admin/UniteController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Unite;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\User;
use App\Http\Controllers\Controller;

class UniteController extends Controller
{
    protected $titre = "Unités";

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('isAdmin')->only(['edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $titre = $this->titre;
        $unites = Unite::orderBy('nom', 'ASC')->get();
        return view('unites.index', compact('unites', 'titre'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $titre = $this->titre;
        return view('unites.create', compact('titre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $unite = Unite::create(['nom' => $request->nom, 'abreviation' => $request->abreviation]);
        return redirect(route('unite.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Unite  $unite
     * @return \Illuminate\Http\Response
     */
    public function show(Unite $unite)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Unite  $unite
     * @return \Illuminate\Http\Response
     */
    public function edit(Unite $unite)
    {
        $titre = $this->titre;
        return view('unites.edit', compact('unite', 'titre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Unite  $unite
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unite $unite)
    {
        $unite->update($request->all());
        return redirect(route('unite.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Unite  $unite
     * @return \Illuminate\Http\Response
     */
    public function destroy(Unite $unite)
    {
        $unite->delete();
        return redirect(route('unite.index'));
    }
    
    public function recherche(Request $request)
    {
        $titre = $this->titre;
        $recherche = $request->recherche;
        $unites = Unite::where('nom', 'LIKE', '%' . $recherche . '%')->orWhere('id', 'LIKE', $recherche)->orWhere('abreviation', 'LIKE', '%' . $recherche . '%')->orderBy('nom', 'ASC')->get();
        return view('unites.index', compact('unites', 'titre', 'recherche'));
    }
}

resources/views/unites/create.blade.php
@extends('layouts.default')

@section('content')
	<h2>Ajouter une nouvelle unité</h2>
	{!! Form::open(['url' => route('unite.store')]) !!}
		<div class="form-group">
			{!! Form::label('nom', 'Nom : ') !!}
			{!! Form::text('nom', null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('abreviation', 'Abréviation : ') !!}
			{!! Form::text('abreviation', null, ['class' => 'form-control']) !!}
		</div>
		<button class="btn btn-primary">Ajouter</button>
	{!! Form::close() !!}
@endsection

@section('titre', $titre)

resources/views/unites/edit.blade.php
@extends('layouts.default')

@section('content')
	<h2>Editer l'unité</h2>
	{!! Form::open(['method' => 'put', 'url' => route('unite.update', $unite)]) !!}
		<div class="form-group">
			{!! Form::label('nom', 'Nom : ') !!}
			{!! Form::text('nom', $unite['nom'], ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('abreviation', 'Abréviation : ') !!}
			{!! Form::text('abreviation', $unite['abreviation'], ['class' => 'form-control']) !!}
		</div>
		<button class="btn btn-primary">Modifier</button>
	{!! Form::close() !!}
@endsection

@section('titre', $titre)

resources/views/unites/index.blade.php
@extends('layouts.default')

@section('content')
	<h2>Liste des unités</h2>
	<div class="d-flex justify-content-between mt-3">
		{!! Form::open(['url' => 'admin/unite/recherche', 'method' => 'POST', 'class' => 'form-inline mt-2 mt-md-0']) !!}
			{{ Form::text('recherche', $recherche??null, ['class' => 'form-control', 'placeholder' => 'Unité']) }}
			{{ Form::submit('Rechercher', ['class' => 'btn btn-outline-secondary my-2 my-sm-0'])}}
		{!! Form::close() !!}
		@if (Auth::check() && Auth::user()->isAdmin())
		<a class="btn btn-primary" href="{{ route('unite.create') }}">Ajouter une unité</a>
		@endif
	</div>
	@if (isset($unites) && count($unites) != 0)
	<div>
		<table class="table table-striped table-hover text-center">
			<thead class="thead-dark">
				<tr>
					@if (Auth::check() && Auth::user()->isAdmin())
					<th scope="col">Id</th>
					@endif
					<th scope="col">Nom</th>
					<th scope="col">Abréviation</th>
					@if (Auth::check() && Auth::user()->isAdmin())
					<th scope="col">Actions</th>
					@endif
				</tr>
			</thead>
			<tbody>
			@foreach ($unites as $unite)
				<tr>
					@if (Auth::check() && Auth::user()->isAdmin())
					<td>{{ $unite['id'] }}</td>
					@endif
					<td>{{ $unite['nom'] }}</td>
					<td>{{ $unite['abreviation'] }}</td>
					@if (Auth::check() && Auth::user()->isAdmin())
					<td>
						<div>
							<a class="d-inline-block btn btn-success" href="{{ route('unite.edit', ['unite' => $unite]) }}">Modifier</a>
							{!! Form::open(['action' => ['Admin\UniteController@destroy', 'unite' => $unite], 'method' => 'POST', 'class' => 'd-inline-block']) !!}
								{{ Form::hidden('_method', 'DELETE') }}
								{{ Form::submit('Supprimer', ['class' => 'btn btn-danger'])}}
							{!! Form::close() !!}
						</div>
					</td>
					@endif
				</tr>
			@endforeach
			</tbody>
		</table>
	</div>
	@else
	<div>
		Aucune unité dans la base de donnée !
	</div>
	@endif
@endsection

@section('titre', $titre)